"""
Django settings for bangalore_days project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

from pathlib import Path


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = 'django-insecure-&v95633&@2_^gwbt-lp752)0o=h$w%ia%g78xpz&dpccfcs_4-'

DEBUG = True

ALLOWED_HOSTS = []


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Jazzmin MUST come before django.contrib.admin
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


# ============================================================
# JAZZMIN ADMIN SETTINGS
# ============================================================

JAZZMIN_SETTINGS = {

    # --------------------------------------------------------
    # Website / Branding
    # --------------------------------------------------------

    "site_title": "Bangalore Days Admin",

    "site_header": "Bangalore Days",

    "site_brand": "Bangalore Days",

    "site_logo": None,

    "login_logo": None,

    "welcome_sign": "Welcome to Bangalore Days Administration",

    "copyright": "Bangalore Days",

    "search_model": [
        "auth.User",
    ],


    # --------------------------------------------------------
    # Sidebar
    # --------------------------------------------------------

    "show_sidebar": True,

    "navigation_expanded": True,

    "hide_apps": [],

    "hide_models": [],


    # --------------------------------------------------------
    # Sidebar Icons
    # --------------------------------------------------------

    "icons": {

        "auth": "fas fa-users-cog",

        "auth.User": "fas fa-user",

        "auth.Group": "fas fa-users",

    },


    # --------------------------------------------------------
    # UI Behaviour
    # --------------------------------------------------------

    "related_modal_active": True,

    "show_ui_builder": False,

    "changeform_format": "horizontal_tabs",

    "changeform_format_overrides": {},


    # --------------------------------------------------------
    # Top Menu
    # --------------------------------------------------------

    "topmenu_links": [

        {
            "name": "Dashboard",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },

        {
            "name": "Website",
            "url": "/",
            "new_window": False,
        },

    ],


    # --------------------------------------------------------
    # User Menu
    # --------------------------------------------------------

    "usermenu_links": [

        {
            "name": "Website",
            "url": "/",
            "new_window": False,
        },

    ],


    # --------------------------------------------------------
    # Language
    # --------------------------------------------------------

    "language_chooser": False,

}


# ============================================================
# JAZZMIN UI TWEAKS
# ============================================================

JAZZMIN_UI_TWEAKS = {

    # --------------------------------------------------------
    # Theme
    # --------------------------------------------------------

    "theme": "flatly",

    "dark_mode_theme": "darkly",


    # --------------------------------------------------------
    # Navbar
    # --------------------------------------------------------

    "navbar_small_text": False,

    "navbar_fixed": True,

    "navbar": "navbar-white navbar-light",


    # --------------------------------------------------------
    # Sidebar
    # --------------------------------------------------------

    "sidebar_small_text": False,

    "sidebar_fixed": True,

    "sidebar": "sidebar-dark-primary",


    # --------------------------------------------------------
    # Footer
    # --------------------------------------------------------

    "footer_fixed": False,


    # --------------------------------------------------------
    # Layout
    # --------------------------------------------------------

    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,

    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": False,

    "sidebar_nav_legacy_style": False,

    "sidebar_nav_flat_style": True,


    # --------------------------------------------------------
    # Body
    # --------------------------------------------------------

    "body_small_text": False,

    "brand_small_text": False,

    "actions_sticky_top": True,

}


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = 'bangalore_days.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [

    {

        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'bangalore_days.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

DATABASES = {

    'default': {

        'ENGINE':
            'django.db.backends.sqlite3',

        'NAME':
            BASE_DIR / 'db.sqlite3',

    }

}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'