"""
Django settings for banglore_days project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path

# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = 'django-insecure-5r2y^hud==c2k7y)5qi6wg04pi%v9r6&6$=i^_)h$_45loxk'

# Development only
# Change this to False in production
DEBUG = True

ALLOWED_HOSTS = []


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Jazzmin Admin Theme
    'jazzmin',

    # Django Default Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your custom apps will be added here later
    # Example:
    # 'products',
    # 'users',
    # 'cart',
    # 'orders',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = 'banglore_days.urls'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # We will add our custom template folder here later
        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = 'banglore_days.wsgi.application'


# ============================================================
# DATABASE
# ============================================================

# SQLite database for development

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'

# Directory where Django will collect static files
# when we run: python manage.py collectstatic

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional static files directory
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ============================================================
# MEDIA FILES
# ============================================================

# User-uploaded files such as:
# - Product images
# - Profile pictures
# - Category images

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# EMAIL CONFIGURATION
# ============================================================

# During development, emails will appear in the terminal
# instead of actually being sent.

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ============================================================
# JAZZMIN ADMIN CONFIGURATION
# ============================================================

JAZZMIN_SETTINGS = {

    # Browser tab title
    "site_title": "Banglore Days Admin",

    # Text displayed in the admin header
    "site_header": "Banglore Days",

    # Branding
    "site_brand": "Banglore Days",

    # Welcome message on admin login/dashboard
    "welcome_sign": "Welcome to Banglore Days Admin",

    # Footer copyright
    "copyright": "Banglore Days",

    # Show sidebar
    "show_sidebar": True,

    # Expand navigation automatically
    "navigation_expanded": True,

    # Keep Django's default logout behavior
    "user_avatar": None,

    # Apps/models that should be hidden
    "hide_apps": [],

    "hide_models": [],

    # Icons for Django default models
    "icons": {

        "auth": "fas fa-users-cog",

        "auth.user": "fas fa-user",

        "auth.Group": "fas fa-users",

    },

    # Top menu links
    "topmenu_links": [

        {
            "name": "Home",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },

    ],

    # User menu
    "usermenu_links": [

        {
            "name": "Support",
            "url": "#",
        },

    ],

}


# ============================================================
# JAZZMIN UI CUSTOMIZATION
# ============================================================

JAZZMIN_UI_TWEAKS = {

    # Navbar
    "navbar_small_text": False,

    # Footer
    "footer_small_text": False,

    # Body
    "body_small_text": False,

    # Brand
    "brand_small_text": False,

    # Accent color
    "accent": "accent-primary",

    # Navbar style
    "navbar": "navbar-dark",

    # Sidebar style
    "sidebar": "sidebar-dark-primary",

    # Sidebar text
    "sidebar_nav_small_text": False,

    # Sidebar expansion
    "sidebar_disable_expand": False,

    # Main theme
    "theme": "default",

    # Dark mode theme
    "dark_mode_theme": "darkly",

}